# Generated by Django 2.2.4 on 2019-10-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRANSACTION_ID', models.CharField(max_length=20)),
                ('PHONE_NUMBER', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
