# Generated by Django 2.2.4 on 2019-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='PHONE_NUMBER',
            field=models.IntegerField(),
        ),
    ]
